name       : glabels
version    : 3.4.1
release    : 3
source     :
    - https://download.gnome.org/sources/glabels/3.4/glabels-3.4.1.tar.xz : 18e457298abb1c617187361109eeae769317686303fc07726af31e11519c5938
license    : GPL-3.0-or-later
component  : office
summary    : gLabels is a program for creating labels and business cards.
description: |
    gLabels is a program for creating labels and business cards.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libqrencode)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
