name       : glabels
version    : 3.4.0
release    : 1
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/glabels/3.4/glabels-3.4.0.tar.xz : d40e079395d30adbcd8204f41d08f7a8da9ec130bffa4cb3c130fbe2322b6410
license    : GPL-3.0
component  : office
summary    : gLabels is a program for creating labels and business cards. 
description: |
    gLabels is a program for creating labels and business cards. 
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libqrencode)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
